# Generated by Django 2.0.2 on 2018-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField()),
                ('account_name', models.CharField(max_length=255)),
                ('account_bank', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_cccount_info',
            },
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
